### ISSUE TITLE
Run java example and datanode panicked 

### ISSUE THREAD

**Issue by Tianpingan** [AutoMQ/elastic-stream#367]
```
2023-05-29 08:18:23 | TRACE | components/client/src/response.rs:293 — Received Report Metrics response: ReportMetricsResponse { data_node: Some(DataNode { node_id: 0, advertise_addr: "127.0.0.1:10911" }), status: Status { code: OK, message: None, detail: None } }
2023-05-29 08:18:23 | TRACE | components/transport/src/connection.rs:77 — Read 97 bytes from 127.0.0.1:48434
2023-05-29 08:18:23 | TRACE | components/codec/src/frame.rs:92 — Incoming frame length is: 93
2023-05-29 08:18:24 | TRACE | components/transport/src/connection.rs:77 — Read 80 bytes from 127.0.0.1:48434
2023-05-29 08:18:24 | TRACE | components/codec/src/frame.rs:92 — Incoming frame length is: 76
thread 'DataNode[Primary]' panicked at 'not yet implemented', data-node/src/handler/cmd.rs:57:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-05-29 08:18:24 | TRACE | components/transport/src/connection.rs:77 — Read 148 bytes from 127.0.0.1:48434
2023-05-29 08:18:24 | TRACE | components/codec/src/frame.rs:92 — Incoming frame length is: 144
2023-05-29 08:18:24 | TRACE | components/transport/src/connection.rs:179 — Get 180 bytes to write to: 1
```
`thread 'DataNode[Primary]' panicked at 'not yet implemented', data-node/src/handler/cmd.rs:57:17`
<img width="736" alt="image" src="https://github.com/AutoMQ/elastic-stream/assets/66737829/75441841-a435-4847-867a-356e75b02300">

It seems that java-sdk send `DescribePlacementManager` to datanode, not the pm
<img width="946" alt="image" src="https://github.com/AutoMQ/elastic-stream/assets/66737829/a36b4b30-1580-43c1-9532-fa2ae42c51a0">

**Comment by Tianpingan** [comment]
I also run rust example and got the same result.

**Comment by lizhanhui** [comment]
Two issues: 
1. data-node shall reject unsupported commands explicitly;
2. Inspect why composite-session sends DescribePlacementManage request to data-node
