### ISSUE TITLE
stream#get loss callback

### ISSUE THREAD

**Issue by superhx** [AutoMQ/elastic-stream#374]
```
root@wumu-dev:~# grep -10 0x00000000fd06ce70 568167.jstack*
568167.jstack-  at java.util.concurrent.DelayQueue.poll(java.base@11.0.18/DelayQueue.java:265)
568167.jstack-  at kafka.server.ClientQuotaManager$ThrottledChannelReaper.doWork(ClientQuotaManager.scala:220)
568167.jstack-  at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
568167.jstack-
568167.jstack-   Locked ownable synchronizers:
568167.jstack-  - None
568167.jstack-
568167.jstack-"Thread-0" #49 daemon prio=5 os_prio=0 cpu=888.94ms elapsed=998.33s tid=0x00007f7fdc210800 nid=0x8ae12 waiting on condition  [0x00007f800e3fb000]
568167.jstack-   java.lang.Thread.State: WAITING (parking)
568167.jstack-  at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
568167.jstack:  - parking to wait for  <0x00000000fd06ce70> (a java.util.concurrent.CompletableFuture$Signaller)
568167.jstack-  at java.util.concurrent.locks.LockSupport.park(java.base@11.0.18/LockSupport.java:194)
568167.jstack-  at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.18/CompletableFuture.java:1796)
568167.jstack-  at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.18/ForkJoinPool.java:3128)
568167.jstack-  at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.18/CompletableFuture.java:1823)
568167.jstack-  at java.util.concurrent.CompletableFuture.get(java.base@11.0.18/CompletableFuture.java:1998)
568167.jstack-  at kafka.log.es.ElasticLogFileRecords$StreamSegmentInputStream.nextBatch(ElasticLogFileRecords.java:227)
568167.jstack-  at kafka.log.es.ElasticLogFileRecords$StreamSegmentInputStream.nextBatch(ElasticLogFileRecords.java:201)
568167.jstack-  at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:37)
568167.jstack-  at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:26)
568167.jstack-  at org.apache.kafka.common.utils.AbstractIterator.maybeComputeNext(AbstractIterator.java:79)
--
568167.jstack1- at java.util.concurrent.DelayQueue.poll(java.base@11.0.18/DelayQueue.java:265)
568167.jstack1- at kafka.server.ClientQuotaManager$ThrottledChannelReaper.doWork(ClientQuotaManager.scala:220)
568167.jstack1- at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
568167.jstack1-
568167.jstack1-   Locked ownable synchronizers:
568167.jstack1- - None
568167.jstack1-
568167.jstack1-"Thread-0" #49 daemon prio=5 os_prio=0 cpu=888.94ms elapsed=1204.78s tid=0x00007f7fdc210800 nid=0x8ae12 waiting on condition  [0x00007f800e3fb000]
568167.jstack1-   java.lang.Thread.State: WAITING (parking)
568167.jstack1- at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
568167.jstack1: - parking to wait for  <0x00000000fd06ce70> (a java.util.concurrent.CompletableFuture$Signaller)
568167.jstack1- at java.util.concurrent.locks.LockSupport.park(java.base@11.0.18/LockSupport.java:194)
568167.jstack1- at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.18/CompletableFuture.java:1796)
568167.jstack1- at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.18/ForkJoinPool.java:3128)
568167.jstack1- at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.18/CompletableFuture.java:1823)
568167.jstack1- at java.util.concurrent.CompletableFuture.get(java.base@11.0.18/CompletableFuture.java:1998)
568167.jstack1- at kafka.log.es.ElasticLogFileRecords$StreamSegmentInputStream.nextBatch(ElasticLogFileRecords.java:227)
568167.jstack1- at kafka.log.es.ElasticLogFileRecords$StreamSegmentInputStream.nextBatch(ElasticLogFileRecords.java:201)
568167.jstack1- at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:37)
568167.jstack1- at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:26)
568167.jstack1- at org.apache.kafka.common.utils.AbstractIterator.maybeComputeNext(AbstractIterator.java:79)
```

**Comment by lizhanhui** [comment]
https://github.com/AutoMQ/elastic-stream/pull/381

**Comment by superhx** [comment]
AutoMQ for Kafka callback deadlock
