### ISSUE TITLE
"subtract with overflow" when collecting metrics

### ISSUE THREAD

**Issue by Chillax-0v0** [AutoMQ/elastic-stream#440]
data node logs:
```
Jun 05 13:51:47 ip-10-0-0-49 data-node[33201]: thread 'DataNode[Primary]' panicked at 'attempt to subtract with overflow', components/observation/src/metrics/uring_metrics.rs:84:24
Jun 05 13:51:47 ip-10-0-0-49 data-node[33201]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 05 13:51:47 ip-10-0-0-49 systemd[1]: data-node.service: Main process exited, code=killed, status=6/ABRT
Jun 05 13:51:47 ip-10-0-0-49 systemd[1]: data-node.service: Failed with result 'signal'.
```

**Comment by Chillax-0v0** [comment]
another case:
```
Jun 06 11:45:39 dn1 data-node[21897]: thread 'DataNode[Primary]' panicked at 'attempt to subtract with overflow', components/observation/src/metrics/store_metrics.rs:138:24
Jun 06 11:45:39 dn1 data-node[21897]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 06 11:45:39 dn1 systemd[1]: data-node.service: Main process exited, code=killed, status=6/ABRT
Jun 06 11:45:39 dn1 systemd[1]: data-node.service: Failed with result 'signal'.
Jun 06 11:45:39 dn1 systemd[1]: data-node.service: Consumed 3min 10.812s CPU time.
Jun 06 11:45:40 dn1 systemd[1]: data-node.service: Scheduled restart job, restart counter is at 1.
Jun 06 11:45:40 dn1 systemd[1]: Stopped Data Node.
Jun 06 11:45:40 dn1 systemd[1]: data-node.service: Consumed 3min 10.812s CPU time.
```
