### ISSUE TITLE
wal recover panic 

### ISSUE THREAD

**Issue by superhx** [AutoMQ/elastic-stream#523]
```
Jun 12 05:52:31 ip-10-0-0-153 data-node[74979]: thread 'IO' panicked at 'attempt to subtract with overflow', components/store/src/io/wal.rs:146:28
Jun 12 05:52:31 ip-10-0-0-153 data-node[74979]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 12 05:52:31 ip-10-0-0-153 systemd[1]: data-node.service: Main process exited, code=killed, status=6/ABRT
Jun 12 05:52:31 ip-10-0-0-153 systemd[1]: data-node.service: Failed with result 'signal'.
Jun 12 05:52:32 ip-10-0-0-153 systemd[1]: data-node.service: Scheduled restart job, restart counter is at 4.
Jun 12 05:52:32 ip-10-0-0-153 systemd[1]: Stopped Data Node.
Jun 12 05:52:32 ip-10-0-0-153 systemd[1]: Started Data Node.
Jun 12 05:52:32 ip-10-0-0-153 data-node[75033]: thread 'IO' panicked at 'attempt to subtract with overflow', components/store/src/io/wal.rs:146:28
Jun 12 05:52:32 ip-10-0-0-153 data-node[75033]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 12 05:52:32 ip-10-0-0-153 systemd[1]: data-node.service: Main process exited, code=killed, status=6/ABRT
Jun 12 05:52:32 ip-10-0-0-153 systemd[1]: data-node.service: Failed with result 'signal'.
Jun 12 05:52:33 ip-10-0-0-153 systemd[1]: data-node.service: Scheduled restart job, restart counter is at 5.
Jun 12 05:52:33 ip-10-0-0-153 systemd[1]: Stopped Data Node.
Jun 12 05:52:33 ip-10-0-0-153 systemd[1]: Started Data Node.
Jun 12 05:52:33 ip-10-0-0-153 data-node[75087]: thread 'IO' panicked at 'attempt to subtract with overflow', components/store/src/io/wal.rs:146:28
Jun 12 05:52:33 ip-10-0-0-153 data-node[75087]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 12 05:52:33 ip-10-0-0-153 systemd[1]: data-node.service: Main process exited, code=killed, status=6/ABRT
Jun 12 05:52:33 ip-10-0-0-153 systemd[1]: data-node.service: Failed with result 'signal'.
```

**Comment by lizhanhui** [comment]
Fixed
