### ISSUE TITLE
SegmentFault at range-server flush rocksdb when quit

### ISSUE THREAD

**Issue by lizhanhui** [AutoMQ/elastic-stream#832]
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007efe88f5f423 in rocksdb::EnvLogger::Logv(char const*, __va_list_tag*) () from /usr/local/lib/librocksdb.so.8.1
#2  0x00007efe88f56019 in rocksdb::Logger::Logv(rocksdb::InfoLogLevel, char const*, __va_list_tag*) [clone .part.0] () from /usr/local/lib/librocksdb.so.8.1
#3  0x00007efe88f5936a in rocksdb::Log(rocksdb::InfoLogLevel, std::shared_ptr<rocksdb::Logger> const&, char const*, ...) () from /usr/local/lib/librocksdb.so.8.1
#4  0x00007efe88dc2edc in rocksdb::DBImpl::Flush(rocksdb::FlushOptions const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> > const&) () from /usr/local/lib/librocksdb.so.8.1
#5  0x00007efe88cf28d7 in rocksdb_flush_cfs () from /usr/local/lib/librocksdb.so.8.1
#6  0x00005595a6b17945 in rocksdb::db::DBCommon<rocksdb::db::SingleThreaded, rocksdb::db::DBWithThreadModeInner>::flush_cfs_opt<rocksdb::db::SingleThreaded, rocksdb::db::DBWithThreadModeInner, rocksdb::column_family::ColumnFamily> (
    self=0x5595a9ad7750, cfs=..., opts=0x7efe63ffb4f8) at /root/.cargo/git/checkouts/rust-rocksdb-2e5fdf98ef21e8dc/3d09d26/src/db.rs:930
#7  0x00005595a6afc6da in store::index::indexer::Indexer::flush (self=0x5595a9ad7750, wait=true) at components/store/src/index/indexer.rs:362
#8  0x00005595a6b6f52b in store::io::uring::IO::run (io=..., recovery_completion_tx=...) at components/store/src/io/uring.rs:1444
#9  0x00005595a6ad5603 in store::store::elastic_store::{impl#0}::new::{closure#0} () at components/store/src/store/elastic_store.rs:117
#10 0x00005595a6ad5ae9 in store::store::elastic_store::{impl#0}::with_thread::{closure#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}> () at components/store/src/store/elastic_store.rs:143
#11 0x00005595a6af2b19 in std::sys_common::backtrace::__rust_begin_short_backtrace<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()> (f=...)
    at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:135
#12 0x00005595a6aa8ce2 in std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure#0}<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()> ()
    at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/thread/mod.rs:529
#13 0x00005595a6b736f2 in core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()>> (self=...) at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/panic/unwind_safe.rs:271
#14 0x00005595a6b5a9ca in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()>>, ()> (data=0x7efe63ffe2d0) at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:500
#15 0x00005595a6b5ab0b in __rust_try ()
#16 0x00005595a6b5a831 in std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()>>> (f=...) at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:464
#17 0x00005595a6aa86ae in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()>>, ()> (f=...) at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panic.rs:142
#18 std::thread::{impl#0}::spawn_unchecked_::{closure#1}<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()> ()
    at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/thread/mod.rs:528
#19 0x00005595a6b3181f in core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<store::store::elastic_store::{impl#0}::with_thread::{closure_env#0}<store::store::elastic_store::{impl#0}::new::{closure_env#0}>, ()>, ()> () at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/ops/function.rs:250
#20 0x00005595a74c5615 in alloc::boxed::{impl#47}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2007
#21 alloc::boxed::{impl#47}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2007
#22 std::sys::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/unix/thread.rs:108
#23 0x00007efe88694b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#24 0x00007efe88726a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by lizhanhui** [comment]
Update:
If RocksDB is built from source, this bug cannot reproduce.
