### ISSUE TITLE
range server start panic

### ISSUE THREAD

**Issue by superhx** [AutoMQ/elastic-stream#868]
Some hint: 
- the store size limit is 10GB
- 500MB/s traffic, and run several seconds panic by other reason.

```
root@ip-172-31-36-32:~/elastic-stream# RUST_BACKTRACE=full ./target/release/range-server start --log etc/range-server-log.yaml
env_posix.cc: SetCpuSet, size = 1
env_posix.cc: cpu_set[0]: 0
thread 'IO' panicked at 'attempt to subtract with overflow', components/store/src/io/wal.rs:174:28
stack backtrace:
   0:     0xaaaaca0f9728 - std::backtrace_rs::backtrace::libunwind::trace::he66faa5ff1f1b48b
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaaca0f9728 - std::backtrace_rs::backtrace::trace_unsynchronized::h78d1fe31b6a704d2
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaaca0f9728 - std::sys_common::backtrace::_print_fmt::h900af4eb0cd5d2a1
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:65:5
   3:     0xaaaaca0f9728 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbbfbc31038647727
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaac9d4ad6c - core::fmt::rt::Argument::fmt::h01dcaedbc00bf4d9
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/fmt/rt.rs:138:9
   5:     0xaaaac9d4ad6c - core::fmt::write::h12736b4677c45c31
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/fmt/mod.rs:1094:21
   6:     0xaaaaca0d2b78 - std::io::Write::write_fmt::h5d383b59ecb67953
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/io/mod.rs:1714:15
   7:     0xaaaaca0fa670 - std::sys_common::backtrace::_print::hc4c6d1eab6123a84
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xaaaaca0fa670 - std::sys_common::backtrace::print::ha34811b1558fc8a4
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xaaaaca0fa2d0 - std::panicking::default_hook::{{closure}}::hdc047983cb9ccfc2
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:269:22
  10:     0xaaaaca0fb194 - std::panicking::default_hook::h0ae77e03268d84fb
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:288:9
  11:     0xaaaaca0fb194 - std::panicking::rust_panic_with_hook::h25eb5bd09e25c026
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:705:13
  12:     0xaaaaca0facac - std::panicking::begin_panic_handler::{{closure}}::h1e190d2b580df09e
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:595:13
  13:     0xaaaaca0fac44 - std::sys_common::backtrace::__rust_end_short_backtrace::h1959eede58f9a3f4
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:151:18
  14:     0xaaaaca0fac38 - rust_begin_unwind
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:593:5
  15:     0xaaaac9c89dc8 - core::panicking::panic_fmt::h391f116960389fda
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/panicking.rs:67:14
  16:     0xaaaac9c89ee4 - core::panicking::panic::ha47e2f6cb2806268
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/panicking.rs:117:5
  17:     0xaaaaca1146a4 - store::io::uring::IO::run::h9552a28990ab1001
  18:     0xaaaaca10a4ac - std::sys_common::backtrace::__rust_begin_short_backtrace::heddce94f2e637f00
  19:     0xaaaaca108f90 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdca28decc16c5e07
  20:     0xaaaaca0fc7f4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha35a47fc334fa0bb
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/alloc/src/boxed.rs:2007:9
  21:     0xaaaaca0fc7f4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hae314932f47244e7
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/alloc/src/boxed.rs:2007:9
  22:     0xaaaaca0fc7f4 - std::sys::unix::thread::Thread::new::thread_start::h4d43f3de489a2703
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys/unix/thread.rs:108:17
```

**Comment by lizhanhui** [comment]
Fixed
