### ISSUE TITLE
Range server Log internal store error

### ISSUE THREAD

**Issue by superhx** [AutoMQ/elastic-stream#870]
Empty cluster run with 500MB/s traffic.
```
root@ip-172-31-36-32:~/elastic-stream# RUST_BACKTRACE=full ./target/release/range-server start --log etc/range-server-log.yaml
env_posix.cc: SetCpuSet, size = 1
env_posix.cc: cpu_set[0]: 0
Failed to create I/O Uring instance
thread 'IO' panicked at 'not yet implemented: Log internal store error', components/store/src/store/elastic_store.rs:139:17
stack backtrace:
   0:     0xaaaae2e59728 - std::backtrace_rs::backtrace::libunwind::trace::he66faa5ff1f1b48b
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaae2e59728 - std::backtrace_rs::backtrace::trace_unsynchronized::h78d1fe31b6a704d2
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaae2e59728 - std::sys_common::backtrace::_print_fmt::h900af4eb0cd5d2a1
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:65:5
   3:     0xaaaae2e59728 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbbfbc31038647727
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaae2aaad6c - core::fmt::rt::Argument::fmt::h01dcaedbc00bf4d9
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/fmt/rt.rs:138:9
   5:     0xaaaae2aaad6c - core::fmt::write::h12736b4677c45c31
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/fmt/mod.rs:1094:21
   6:     0xaaaae2e32b78 - std::io::Write::write_fmt::h5d383b59ecb67953
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/io/mod.rs:1714:15
   7:     0xaaaae2e5a670 - std::sys_common::backtrace::_print::hc4c6d1eab6123a84
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xaaaae2e5a670 - std::sys_common::backtrace::print::ha34811b1558fc8a4
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xaaaae2e5a2d0 - std::panicking::default_hook::{{closure}}::hdc047983cb9ccfc2
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:269:22
  10:     0xaaaae2e5b194 - std::panicking::default_hook::h0ae77e03268d84fb
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:288:9
  11:     0xaaaae2e5b194 - std::panicking::rust_panic_with_hook::h25eb5bd09e25c026
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:705:13
  12:     0xaaaae2e5acac - std::panicking::begin_panic_handler::{{closure}}::h1e190d2b580df09e
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:595:13
  13:     0xaaaae2e5ac44 - std::sys_common::backtrace::__rust_end_short_backtrace::h1959eede58f9a3f4
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys_common/backtrace.rs:151:18
  14:     0xaaaae2e5ac38 - rust_begin_unwind
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:593:5
  15:     0xaaaae29e9dc8 - core::panicking::panic_fmt::h391f116960389fda
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/panicking.rs:67:14
  16:     0xaaaae2e6a54c - std::sys_common::backtrace::__rust_begin_short_backtrace::heddce94f2e637f00
  17:     0xaaaae2e68f90 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdca28decc16c5e07
  18:     0xaaaae2e5c7f4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha35a47fc334fa0bb
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/alloc/src/boxed.rs:2007:9
  19:     0xaaaae2e5c7f4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hae314932f47244e7
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/alloc/src/boxed.rs:2007:9
  20:     0xaaaae2e5c7f4 - std::sys::unix::thread::Thread::new::thread_start::h4d43f3de489a2703
                               at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/sys/unix/thread.rs:108:17
```

**Comment by superhx** [comment]
```
2023-08-03 01:21:13.515 | INFO  | components/store/src/io/uring.rs:1353 — store::io::uring Failed to push SQE entries into submission queue: PushError
```

![image](https://github.com/AutoMQ/elastic-stream/assets/5719209/b28485cf-6349-4c22-adf5-23d293d4cdb2)

**Comment by Chillax-0v0** [comment]
Reducing the value of `1store.uring.queue-depth` in the range-server.yaml file can solve this problem.

**Comment by superhx** [comment]
> Reducing the value of `store.uring.queue-depth` in the `range-server.yaml` can solve this problem.

The issue is another problem

**Comment by lizhanhui** [comment]
The last write op may be spitted into two Write SQEs, exceeding the configured queue depth
